### ISSUE TITLE
ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by virtuaklem** [h3x4d3c1m4l/Blazor.LoadingIndicator#1]
Hi, 

I create a new Blazor Server Project and i want use your loading component. But, when i tries this, i have an internal server error : 

```
ArgumentNullException: Value cannot be null. (Parameter 'key')
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.ThrowKeyNullException()
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.TryGetValue(TKey key, out TValue value)
    Blazor.LoadingIndicator.Loading.UnsubscribeFromTaskProgressChanged(string context, Action<ITaskStatus> action)
    Blazor.LoadingIndicator.Indicator.Dispose()
    Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
    Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)
    Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
    Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)
    Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose()
    Microsoft.AspNetCore.Mvc.ViewFeatures.RazorComponents.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
    Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentExtensions.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
    Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentExtensions.RenderComponentAsync<TComponent>(IHtmlHelper htmlHelper, RenderMode renderMode, object parameters)
    Search_Blazor.Pages.Pages__Host.<ExecuteAsync>b__15_1() in _Host.cshtml

            @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
```

I just copy your sample : 
`@using Blazor.LoadingIndicator`

Add : 
```
<Indicator Context="on-init">
        <p>I'm successfully initialized!</p>
   </Indicator>
```

And : 

```
protected` override async Task OnInitializedAsync()
    {
        await Loading.StartTaskAsync(async (task) =>
        {
            await Task.Delay(5000);
        }, "on-init", "Initializing", "Please wait ...");
    
    }
```

What's wrong ? Your component can be use in blazor server template ?

Have a good day.

**Comment by h3x4d3c1m4l** [comment]
Hi!

I never tested it on serverside rendered Blazor, but it should be possible.
Could you possibly provide me with a zip file with your project (or a new project with just this code isolated)? I'll have a look into it as soon as possible :)

Thanks!

- Sander

**Comment by Ghitor82** [comment]
I have the same error

**Comment by h3x4d3c1m4l** [comment]
@Ghitor82 Would you mind to isolate the code into a new project and upload it somewhere? This makes it a lot easier for me to reproduce and provide a fix :)

**Comment by Ghitor82** [comment]
I send you the code by email.

**Comment by h3x4d3c1m4l** [comment]
Got it, I took a short look at it. A few observations:

- You are using the NuGet package, I would rather suggest (just for now, until Blazor it stable so I can stabilize this library) to add the git repo as submodule to your project and add the project to your `.sln`
- I see from the `.csproj` that you are running on .NET Core 3.1, I would only advise to run on .NET Core 3.1 if you want to use the Blazor WebAssembly mode
  - As I see from the `Startup.cs` (the `services.AddServerSideBlazor();` statement) you are using serverside Blazor, which I think was stabilized in .NET Core 3.0, thus I would advise to stick to .NET Core 3.0 if possible

I will create a .NET Core 3.1 branch whenever I have some spare time to do it

**Comment by h3x4d3c1m4l** [comment]
Project has been upgraded to .NET Core 3.1 as it is stable now and the recommended version for new .NET projects.

Please try on .NET Core 3.1 using this new version of the code. Please let me know if I can be of any assistance by reopening this issue.
