### ISSUE TITLE
Can't find AddLoadingIndicator

### ISSUE THREAD

**Issue by thiagoloureiro** [h3x4d3c1m4l/Blazor.LoadingIndicator#5]
I'm using Blazor with .NET Core 3.1
installed the nuget package:

"H3x.Blazor.LoadingIndicator" Version="0.2.8-preview.7" 

on Startup.cs I got:

`using Blazor.LoadingIndicator`

but AddLoadingIndicator don't work:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IServiceCollection' does not contain a definition for 'AddLoadingIndicator' and no accessible extension method 'AddLoadingIndicator' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	MI.UserManager	C:\Projects\mi-usermanager\Startup.cs	25	Active

```

**Comment by h3x4d3c1m4l** [comment]
Hi thiagoloureiro,

The NuGet package has not been updated yet. Please don't use it yet.
For the moment the best solution would be to add this repository as a git submodule to your project and add the Blazor.LoadingIndicator project to your solution.

Or download the code as archive from github and extract it next to your project.
