### ISSUE TITLE
Consider retargeting for LGPL

### ISSUE THREAD

**Issue by pablopioli** [h3x4d3c1m4l/Blazor.LoadingIndicator#6]
Currently the library is under the GPL license, this can be a problem in a lot of projects.

For only a library all the source code must be public. Using LGPL allows anyone to use it as a library, but cannot include directly the source code in other applications.

**Comment by h3x4d3c1m4l** [comment]
Hi, thanks for bringing this to my attention.

I will consider it en will let you know soon.

**Comment by h3x4d3c1m4l** [comment]
Fixed by 81c1a191eb5623cd0a05638441e0195b8294c90a!
